fieldLayouts:
  2bdfde7a-cf03-4814-b4e1-cdcb54e93b50:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 089d60bd-21d8-4870-b0ec-6dbcf81f062d # ImageProduct
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5eba5d62-c570-4ea7-a100-c3a15f1e2f7a
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7b5a1479-c1c2-4a59-9d7e-f332837da300
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 60c1010b-8840-493a-9859-23eccd8c7fd4 # Colorway
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddee4bee-3cfe-4619-8a89-eb91e7ce422d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7b05b2d5-6a30-42e8-8710-bfc6b784eaba # Price
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e30bff77-3427-4654-89ee-3e1d7fa7f012
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cb2cc859-73b5-4726-a4f8-c56e793646a2 # Details
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba17f18a-aecc-4f81-8468-04f72aa41f2b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1ac293d1-cf8c-421f-9c6a-850a3937e566
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: ad29d7f1-8453-462d-a7d7-0c578d2a6ee6 # DetailsProduct
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
