defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  ccc03508-0607-4965-a9b2-eea81d347ca3: # Furnitures
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
